version: '3'

services:

  djangoapp:
    build: .
    volumes:
      - .:/opt/services/djangoapp/src
      - static_volume:/opt/services/djangoapp/static  # <-- bind the static volume
      - media_volume:/opt/services/djangoapp/media  # <-- bind the media volume
    networks:
      - nginx_network
      - database1_network
    depends_on:
      - database1
    environment:
      - DEBUG=1
    restart: on-failure
    container_name: djangoapp
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  nginx:
    image: nginx:1.13
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/opt/services/djangoapp/static  # <-- bind the static volume
      - media_volume:/opt/services/djangoapp/media  # <-- bind the media volume
    depends_on:
      - djangoapp
      - node
    networks:
      - nginx_network
    restart: on-failure
    container_name: nginx

  database1:
    image: postgres:12
    expose:
      - 5432
    env_file:
      - config/db/database1_env
    networks:
      - database1_network
    volumes:
      - database1_volume:/var/lib/postgresql/data
    restart: on-failure
    container_name: database1

  node:
    build: ./config/node
    command: sh -c "npm install && npm start"
    volumes:
      - .:/opt/services/djangoapp/src
      - static_volume:/opt/services/djangoapp/static  # <-- bind the static volume
    restart: on-failure
    container_name: node

networks:
  nginx_network:
    driver: bridge
  database1_network:
    driver: bridge

volumes:
  database1_volume:
  static_volume:  # <-- declare the static volume
  media_volume:  # <-- declare the media volume
  source_code_volume:  # <-- declare the media volume

